### ISSUE TITLE
Reference duplication

### ISSUE THREAD

**Issue by i64** [Battery-Intelligence-Lab/DTWpp#14]
Hi authors, I am reviewing the code from [openjournals/joss-reviews#6881](https://github.com/openjournals/joss-reviews/issues/6881#issue-2349216956).

The reference "The UCR Time Series Classification Archive" is duplicated [[1](https://github.com/Battery-Intelligence-Lab/dtw-cpp/blob/4e3b51ef5b6bce9ccbc6690cb755bfbb0350d548/joss/paper.bib#L114-L120), [2](https://github.com/Battery-Intelligence-Lab/dtw-cpp/blob/4e3b51ef5b6bce9ccbc6690cb755bfbb0350d548/joss/paper.bib#L65-L73)] in the bibliography.

**Comment by ElektrikAkar** [comment]
Hi i64, 

Thank you! We changed one of the references with the [IEEE paper](https://doi.org/10.1109/JAS.2019.1911747) and other with the [data repository](https://www.cs.ucr.edu/~eamonn/time_series_data_2018/). 

See 4750f5837be4a97807b2e69cf92e98f66887fcfe for the details.

**Comment by i64** [comment]
Hi @ElektrikAkar,

I checked the commit. LGTM!
