### ISSUE TITLE
Community guideline improvement

### ISSUE THREAD

**Issue by i64** [Battery-Intelligence-Lab/DTWpp#15]
Hi authors, I am reviewing the code from [openjournals/joss-reviews#6881](https://github.com/openjournals/joss-reviews/issues/6881#issue-2349216956).

The "develop" folder contains community guidelines. It could improved to better cover the second item in "Community Guidlines" in the JOSS' checklist.

**Comment by ElektrikAkar** [comment]
Hi i64,

Thank you very much for your comment. We have updated our [community guidelines](https://github.com/Battery-Intelligence-Lab/dtw-cpp/blob/main/CONTRIBUTING.md) along with our [conventions](https://github.com/Battery-Intelligence-Lab/dtw-cpp/blob/main/develop/conventions.md).

We have also added these guidelines to the [latest section](https://battery-intelligence-lab.github.io/dtw-cpp/7_develop/CONTRIBUTING.html) of our documentation website, making it easier for prospective contributors to find them. 

Please see commit c9244b665df8af12c4301aec296da5ee8f10c7d4 for more details.

**Comment by i64** [comment]
Hi @ElektrikAkar,

I checked the commit. LGTM!
